Add systemd suspend service and credits for sources

diff --git a/.config/i3/i3lock-pixelated b/.config/i3/i3lock-pixelated
--- a/.config/i3/i3lock-pixelated
+++ b/.config/i3/i3lock-pixelated
@@ -1,29 +1,85 @@
 #!/usr/bin/env bash
 
-# Take blurred screenshot of current screen
-# sleep 1 && scrot /tmp/lock.png
+prelock() {
+    if [ ! -z "$(pidof dunst)" ]; then
+        pkill -u "$USER" -USR1 dunst
+    fi
+}
 
-# Use the taken screenshot as bg , grayscale it and add an overlay with i3lock-extra
+postlock() {
+    if [ ! -z "$(pidof dunst)" ] ; then
+        pkill -u "$USER" -USR2 dunst
+    fi
+}
+
+lock(){
+    prelock
+
+    # rectangles=" "
+    # SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
+    # for RES in $SR; do
+    #   SRA=(${RES//[x+]/ })
+    #   CX=$((${SRA[2]} + 25))
+    #   CY=$((${SRA[1]} - 30))
+    #   rectangles+="rectangle $CX,$CY $((CX+300)),$((CY-80)) "
+    # done
+
+    # scrot /tmp/lock.png
+    # convert /tmp/lock.png -draw "fill rgba(0, 0, 0, 0.4) $rectangles" /tmp/lock2.png
+
+    letterEnteredColor="#d23c3dff"
+    letterRemovedColor="#d23c3dff"
+    passwordCorrect="#00000000"
+    passwordIncorrect="#d23c3dff"
+    background="#00000000"
+    foreground="#ffffffff"
+    accent="#d23c3dff"
+
+    i3lock-extra -s -g -p --paint -o "$HOME/.config/i3/lock.png" -- -k \
+        --datepos="x+43:h-45" \--date-align 1 --datecolor="$accent" --datestr "%A, %B %d" \
+        --timepos="x+43:h-70" --time-align 1 --timecolor="$accent" \
+        --insidecolor=$background --ringcolor=$foreground --line-uses-inside \
+        --keyhlcolor=$letterEnteredColor --bshlcolor=$letterRemovedColor --separatorcolor=$background \
+        --insidevercolor=$passwordCorrect --insidewrongcolor=$passwordIncorrect \
+        --ringvercolor=$foreground --ringwrongcolor="$foreground" --ring-width=4 \
+        --veriftext="" --wrongtext="GTFO!" --verifcolor="$foreground"  --noinputtext="Empty"
+
+    postlock
+}
 
 
-rectangles=" "
-SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
-for RES in $SR; do
-	SRA=(${RES//[x+]/ })
-	CX=$((${SRA[2]} + 25))
-	CY=$((${SRA[1]} - 30))
-	rectangles+="rectangle $CX,$CY $((CX+300)),$((CY-80)) "
+for arg in "$@"; do
+    [[ "${arg:0:1}" = '-' ]] || continue
+
+    case "$1" in
+
+        -s | --suspend)
+            runsuspend=true
+            ;&
+
+        -l | --lock)
+            runlock=true
+            [[ $runsuspend ]] || lockargs="$lockargs -n"
+            [[ ${2:0:1} = '-' ]] && shift 1 || { lockstyle="$2"; shift 2; }
+            ;;
+
+        *)
+            echo "invalid argument: $1"
+            break
+            ;;
+    esac
 done
 
-scrot /tmp/lock.png
-# convert /tmp/lock.png -draw "fill rgba(0, 0, 0, 0.4) $rectangles" /tmp/lock2.png
 
-letterEnteredColor="#d23c3dff"
-letterRemovedColor="#d23c3dff"
-passwordCorrect="#00000000"
-passwordIncorrect="#d23c3dff"
-background="#00000000"
-foreground="#ffffffff"
-accent="#d23c3dff"
+# Activate lockscreen
+if [[ $runlock ]]; then
+    lock
+    if [[ $runsuspend ]]; then
+        systemctl suspend;
+    else
+        exit 0
+    fi
+else
+    exit 0
+fi
 
-i3lock-extra -s -g -p --paint -o "$HOME/.config/i3/lock.png" -- -k --datepos="x+43:h-45" --date-align 1 --datecolor="$accent" --datestr "%A, %B %d" --timepos="x+43:h-70" --time-align 1 --timecolor="$accent" --insidecolor=$background --ringcolor=$foreground --line-uses-inside --keyhlcolor=$letterEnteredColor --bshlcolor=$letterRemovedColor --separatorcolor=$background --insidevercolor=$passwordCorrect --insidewrongcolor=$passwordIncorrect --ringvercolor=$foreground --ringwrongcolor="$foreground" --ring-width=4 --veriftext="" --wrongtext="GTFO!" --verifcolor="$foreground"  --noinputtext="Empty" 
